# Goals
-> Geopandas

*Check your understanding*
Before diving into this week’s Python lesson, you should already be familiar with some basic spatial data file formats and projection definitions, such as these:

* Shapefile
* GeoPackage
* CRS
* Datum
* EPSG

### Shapefile: 
 A vector data format for storing location information and related attributes. A shapefile consists of several files with a common prefix that need to be stored in the same directory. .shp, .shx, and .dbf are required file extensions in a shapefile. Other file extensions are not required, but for example, the file extension .prj is often essential. More information about Shapefile file extensions is available here. The shapefile format is developed by ESRI.

### GeoPackage:
An open source format for storing and transferring geospatial information. GeoPackages are able to store both vector data and raster data. In more detail, a GeoPackage is a container for an SQLite database with a .gpkg extension (all in one file!). The GeoPackage format is governed by the Open Geospatial Consortium. More information at: https://www.geopackage.org/

### CRS:
Coordinate reference systems define how coordinates relate to real locations on the Earth. Geographic coordinate reference systems commonly use latitude and longitude degrees, while Projected coordinate reference systems use x and y coordinates to represent locations on a flat surface. You will learn more about coordinate reference systems during this lesson!

### Datum:
Defines the center point, orientation, and scale of the reference surface related to a coordinate reference system. The same coordinates can relate to different locations depending on the Datum! For example, WGS84 is a widely used global datum, while ETRS89 is a datum used in Europe. Coordinate reference systems are often named based on the datum used.

### EPSG:
EPSG codes refer to specific reference systems. EPSG stands for “European Petroleum Survey Group,” which originally published a database for spatial reference systems. For example, EPSG:3067 refers to the coordinate reference system ETRS-TM35FIN, commonly used in Finland, while EPSG:4326 refers to WGS84. You can search for EPSG codes at: https://spatialreference.org/

## Vector Data I/O

One of the first steps of many analysis workflow is to read data from a file, one of the last steps often writes data to an output file. To the horror of many geoinformatics scholars, there exist many file formats for GIS data: the old and hated but also loved and established ESRI Shapefile, the universal Geopackage (GPKG), and the web-optimised GeoJSON are just a few of the more well-known examples.

Fear not, Python can read them all (no guarantees, though)!

Most of the current Python GIS packages rely on the GDAL/OGR libraries, for which modern interfaces exist in the form of the fiona and rasterio Python packages.

Today, we’ll concentrate on vector data, so let’s first take a closer look at fiona’s capabilities, and then import and export data using geopandas, which uses fiona under its hood.

### File Formats

#### Fiona

In [10]:
import fiona

fiona.supported_drivers

ModuleNotFoundError: No module named 'fiona'

## Geopandas
To read data from a GeoPackage file into a geopandas.GeoDataFrame (a geospatially-enabled version of a pandas.DataFrame), use geopandas.read_file():

In [ ]:
import geopandas
municipalities = geopandas.read_file(
    DATA_DIRECTORY / "finland_municipalities" / "finland_municipalities_2021.gpkg"
)
municipalities.head()

NameError: name 'DATA_DIRECTORY' is not defined

Reading a local GPKG file is most likely the easiest task for a GIS package. However, in perfect Python ‘Swiss pocket knife’ manner, geopandas can also read Shapefiles inside a ZIP archive, and/or straight from an Internet URL. For example, downloading, unpacking and opening a data set of NUTS regions from the European Union’s GISCO/eurostat download page is one line of code:

In [ ]:
nuts_regions = geopandas.read_file("https://gisco-services.ec.europa.eu/distribution/v2/nuts/shp/NUTS_RG_60M_2021_3035.shp.zip")
nuts_regions.head()

,NUTS_ID,LEVL_CODE,CNTR_CODE,NAME_LATN,NUTS_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,NAME_ENGL,NAME_FREN,ISO3_CODE,SVRG_UN,CAPT,EU_STAT,EFTA_STAT,CC_STAT,NAME_GERM,geometry
0,DE149,3,DE,Sigmaringen,Sigmaringen,4.0,3,3,Germany,Allemagne,DEU,UN Member State,Berlin,T,F,F,Deutschland,"POLYGON ((4272515.778 2791989.118, 4291502.208..."
1,DE211,3,DE,"Ingolstadt, Kreisfreie Stadt","Ingolstadt, Kreisfreie Stadt",4.0,2,3,Germany,Allemagne,DEU,UN Member State,Berlin,T,F,F,Deutschland,"POLYGON ((4430560.572 2849070.969, 4426522.606..."
2,DE212,3,DE,"München, Kreisfreie Stadt","München, Kreisfreie Stadt",4.0,1,3,Germany,Allemagne,DEU,UN Member State,Berlin,T,F,F,Deutschland,"POLYGON ((4426190.454 2780289.957, 4425325.775..."
3,DE213,3,DE,"Rosenheim, Kreisfreie Stadt","Rosenheim, Kreisfreie Stadt",4.0,2,3,Germany,Allemagne,DEU,UN Member State,Berlin,T,F,F,Deutschland,"POLYGON ((4470814.937 2743662.905, 4477767.129..."
4,DE214,3,DE,Altötting,Altötting,4.0,2,3,Germany,Allemagne,DEU,UN Member State,Berlin,T,F,F,Deutschland,"POLYGON ((4539906.565 2792493.475, 4525936.167..."

##### Writing geospatial data to a file

Writing data to a file is equally straight-forward: simply use the `to_file() method <https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.to_file.html#geopandas.GeoDataFrame.to_file>`__ of a GeoDataFrame.

If we want to keep a local copy of the NUTS region data set we just opened on-the-fly from an internet address, the following saves the data to a GeoJSON file (the file format is guessed from the file name):

In [ ]:
nuts_regions.to_file("./europe_nuts_regions.geojson")

##### Reading and writing from and to DB

Geopandas has native support for read/write access to PostgreSQL/PostGIS databases, using its `geopandas.read_postgis() <https://geopandas.org/en/stable/docs/reference/api/geopandas.read_postgis.html>`__ function and the `GeoDataFrame.to_postgis() <https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.to_postgis.html>`__ method. For the database connection, you can use, for instance, the sqlalchemy package.

In [ ]:
import sqlalchemy
DB_CONNECTION_URL = "postgresql://myusername:mypassword@myhost:5432/mydatabase";
db_engine = sqlalchemy.create_engine(DB_CONNECTION_URL)

countries = geopandas.read_postgis(
    "SELECT name, geometry FROM countries",
    db_engine
)
countries.to_postgis(
    "new_table",
    db_engine
)

##### Reading data directly from a WFS (Web Feature Service) endpoint

Geopandas can also read data directly from a WFS endpoint, such as, for instance the geodata APIs of Helsinki Region Infoshare. Constructing a valid WFS URI (address) is not part of this course (but check, for instance, the properties of a layer added to QGIS).

The following code loads a population grid of Helsinki from 2022. The parameters encoded into the WFS address specify the layer name, a bounding box, and the requested reference system.

In [11]:
population_grid = geopandas.read_file(
    "https://kartta.hsy.fi/geoserver/wfs"
    "?service=wfs"
    "&version=2.0.0"
    "&request=GetFeature"
    "&typeName=asuminen_ja_maankaytto:Vaestotietoruudukko_2022"
    "&srsName=EPSG:3879"
    "&bbox=25494767,6671328,25497720,6673701,EPSG:3879",
    crs="EPSG:3879"
)
population_grid.head()

/home/faustino/miniconda3/envs/autogis/lib/python3.11/site-packages/pyogrio/raw.py:200: RuntimeWarning: driver GML does not support open option CRS
  return ogr_read(

,gml_id,index,asukkaita,asvaljyys,ika0_9,ika10_19,ika20_29,ika30_39,ika40_49,ika50_59,ika60_69,ika70_79,ika_yli80,geometry
0,Vaestotietoruudukko_2022.fid-7ff83b93_1a0d6a55...,15177,409,34.99,55,42,49,87,60,47,41,18,10,"POLYGON ((25494750 6671998.997, 25494750 66722..."
1,Vaestotietoruudukko_2022.fid-7ff83b93_1a0d6a55...,15178,285,39.52,21,27,58,66,41,34,26,10,2,"POLYGON ((25494750 6671748.997, 25494750 66719..."
2,Vaestotietoruudukko_2022.fid-7ff83b93_1a0d6a55...,15179,639,40.38,83,55,45,133,123,80,60,48,12,"POLYGON ((25494750 6671498.998, 25494750 66717..."
3,Vaestotietoruudukko_2022.fid-7ff83b93_1a0d6a55...,15180,1684,31.28,143,105,657,383,160,118,81,31,6,"POLYGON ((25494750 6671248.999, 25494750 66714..."
4,Vaestotietoruudukko_2022.fid-7ff83b93_1a0d6a55...,15337,24,36.38,99,99,99,99,99,99,99,99,99,"POLYGON ((25494999.997 6672499.005, 25494999.9..."